name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: "https://api.dobcon.com"
    steps:
      
      - name: Publish summary
        env:
          URL: "https://api.dobcon.com"
        run: |
          echo "Environment URL: $URL: $(($NUM+61000+${{ github.event.pull_request.number }}))" >> $GITHUB_STEP_SUMMARY  
  
