name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: "https://api.dobcon.com"
    steps:
      
      - name: Deployment test message
        run: |
          echo "App deployed"
  
